/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    // implementation("com.google.guava:guava:32.1.1-jre")
    implementation("com.github.kwhat:jnativehook:2.2.2")
    implementation("com.squareup.moshi:moshi:1.14.0")
    // implementation("com.dorkbox:SystemTray:4.4")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("com.ugackminer.unimark.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

fun download(url : String, path : String) {
    val destFile = File(path)
    ant.invokeMethod("get", mapOf("src" to url, "dest" to destFile))
}

// tasks.register<Copy>("copy") {
//    from("app/src/main/resources")
//    into("target")
//    include("**/*.json")
// }

tasks.register("updateShortcodes"){
    val resourcesDir = sourceSets.main.get().getResources().getSrcDirs().iterator().next()
    val sourceUrl = "https://raw.githubusercontent.com/milesj/emojibase/master/packages/data/en/shortcodes/emojibase.raw.json"


    // val moshi : Moshi = Moshi.Builder().build()
    // val jsonAdapter : JSONAdapter<String> = 


    download(sourceUrl, resourcesDir.getPath() + "/test.json")
}

// tasks.register("updateShortcodes") {
//     src("https://raw.githubusercontent.com/milesj/emojibase/master/packages/data/en/shortcodes/emojibase.raw.json");
//     dest(new File(buildDir, "test.json"));
// }